#!/usr/bin/env python3
"""Generate Markdown twins of every indexable HTML page.

For each indexable page (not noindexed, not in an ignored directory) this
script writes a sibling ``.md`` file at the same clean path:

    artists.html      -> artists.md
    it/artists.html   -> it/artists.md
    news/foo.html     -> news/foo.md
    index.html        -> index.md

The twin contains the page title, meta description and the ``<main>`` content
converted to Markdown, with all internal links resolved to absolute clean
URLs (no ``.html``). The first line of every twin is a generator marker so
tooling can tell twins apart from hand-written Markdown; files without the
marker are NEVER overwritten or deleted. Marker-bearing twins whose HTML
source disappeared (or became noindexed) are deleted as orphans.

Deterministic: same input -> byte-identical output (no timestamps).

Usage:
    python3 scripts/generate_md_twins.py            # write twins
    python3 scripts/generate_md_twins.py --check    # verify, no writes
"""

import os
import posixpath
import re
import sys
from urllib.parse import urlsplit, urljoin

from bs4 import BeautifulSoup, NavigableString, Tag
from bs4.element import PreformattedString

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_URL = 'https://milanosensualcongress.com'
MARKER = '<!-- generated by scripts/generate_md_twins.py — do not edit -->'

# Same ignore conventions as scripts/generate_llms_text.py.
IGNORE_PATTERNS = [
    'node_modules', '.git', '.claude', '.agent', '.agents', '.github',
    'tmp', '.gemini', '__pycache__', 'scripts', 'vendor', 'System',
    'google', 'assets', 'images', 'css', 'js', 'fonts',
]

# Elements stripped entirely before conversion.
STRIP_TAGS = [
    'nav', 'footer', 'script', 'style', 'noscript', 'svg', 'form',
    'iframe', 'button', 'input', 'select', 'textarea', 'label', 'template',
    'video', 'audio', 'picture', 'source', 'dialog', 'canvas',
]

# Page widgets that render as noise in text form (countdown timers, reminder
# capture blocks). Matched by element id.
STRIP_IDS = {'countdown', 'reminder-container'}

BLOCK_TAGS = {
    'div', 'section', 'article', 'header', 'aside', 'main', 'figure',
    'figcaption', 'details', 'summary', 'p', 'h1', 'h2', 'h3', 'h4', 'h5',
    'h6', 'ul', 'ol', 'li', 'blockquote', 'table', 'pre', 'hr', 'address',
    'dl', 'dt', 'dd',
}


def should_ignore(rel_path):
    parts = rel_path.replace(os.sep, '/').split('/')
    return any(p in IGNORE_PATTERNS for p in parts)


def clean_url(rel_html_path, fragment=''):
    """Map a repo-relative .html path to its canonical clean URL."""
    rel = rel_html_path.replace(os.sep, '/').lstrip('/')
    if rel == 'index.html':
        url = BASE_URL + '/'
    elif rel.endswith('/index.html'):
        url = f"{BASE_URL}/{rel[:-len('index.html')]}"
    elif rel.endswith('.html'):
        url = f"{BASE_URL}/{rel[:-len('.html')]}"
    else:
        url = f"{BASE_URL}/{rel}"
    if fragment:
        url += '#' + fragment
    return url


def collapse_ws(text):
    return re.sub(r'\s+', ' ', text)


class PageConverter:
    """Convert one HTML page's <main> content to Markdown."""

    def __init__(self, rel_html_path):
        self.rel = rel_html_path.replace(os.sep, '/')
        self.dir = posixpath.dirname(self.rel)

    # ----- link resolution ------------------------------------------------

    def resolve_href(self, href):
        href = href.strip()
        if not href:
            return None
        if href.startswith('#'):
            return clean_url(self.rel, fragment=href[1:])
        parts = urlsplit(href)
        if parts.scheme in ('mailto', 'tel', 'javascript'):
            return href if parts.scheme != 'javascript' else None
        if parts.scheme in ('http', 'https'):
            host = parts.netloc.lower()
            if host in ('milanosensualcongress.com', 'www.milanosensualcongress.com'):
                path = parts.path or '/'
                return self._clean_site_path(path, parts.fragment)
            return href  # external: keep as-is
        if parts.netloc:  # protocol-relative //host/...
            return href
        # Relative link: resolve against this page's directory.
        base = '/' + (self.dir + '/' if self.dir else '')
        resolved = urljoin(base, parts.path or '')
        return self._clean_site_path(resolved, parts.fragment)

    def _clean_site_path(self, abs_path, fragment=''):
        path = posixpath.normpath(abs_path)
        if abs_path.endswith('/') and path != '/':
            path += '/'
        path = path.lstrip('/')
        if path in ('', '.'):
            url = BASE_URL + '/'
        elif path.endswith('.html'):
            return clean_url(path, fragment)
        else:
            url = f'{BASE_URL}/{path}'
        if fragment:
            url += '#' + fragment
        return url

    # ----- inline conversion ----------------------------------------------

    def inline(self, node):
        if isinstance(node, PreformattedString):
            return ''  # comments, CDATA, doctypes
        if isinstance(node, NavigableString):
            return collapse_ws(str(node))
        if not isinstance(node, Tag):
            return ''
        if node.get('aria-hidden') == 'true':
            return ''
        name = node.name
        if name == 'br':
            return ' '
        if name == 'img':
            return ''
        inner = ''.join(self.inline(c) for c in node.children)
        if name == 'a':
            text = collapse_ws(inner).strip()
            url = self.resolve_href(node.get('href') or '')
            if not url:
                return inner
            if not text:
                return ''
            return f'[{text}]({url})'
        if name in ('strong', 'b'):
            text = collapse_ws(inner).strip()
            return f' **{text}** ' if text else ''
        if name in ('em', 'i'):
            text = collapse_ws(inner).strip()
            return f' *{text}* ' if text else ''
        if name == 'code':
            text = collapse_ws(inner).strip()
            return f' `{text}` ' if text else ''
        return inner

    def inline_text(self, node):
        text = collapse_ws(self.inline(node)).strip()
        text = re.sub(r'\*\* ([,.;:!?)])', r'**\1', text)
        text = re.sub(r'([(‘“"]) \*\*', r'\1**', text)
        return text

    # ----- block conversion -----------------------------------------------

    def blocks(self, node, out, list_depth=0):
        for child in node.children:
            if isinstance(child, PreformattedString):
                continue  # comments, CDATA, doctypes
            if isinstance(child, NavigableString):
                text = collapse_ws(str(child)).strip()
                if text:
                    out.append(text)
                continue
            if not isinstance(child, Tag):
                continue
            if child.name in STRIP_TAGS or child.get('aria-hidden') == 'true':
                continue
            name = child.name
            if name in ('h1', 'h2', 'h3', 'h4', 'h5', 'h6'):
                text = self.inline_text(child)
                if text:
                    level = min(int(name[1]) + 1, 6) if name != 'h1' else 1
                    out.append('#' * level + ' ' + text)
            elif name == 'p':
                text = self.inline_text(child)
                if text:
                    out.append(text)
            elif name in ('ul', 'ol'):
                items = []
                ordered = name == 'ol'
                for idx, li in enumerate(child.find_all('li', recursive=False), 1):
                    sub = []
                    self.blocks(li, sub, list_depth + 1)
                    if not sub:
                        continue
                    bullet = f'{idx}.' if ordered else '-'
                    indent = '  ' * list_depth
                    first, rest = sub[0], sub[1:]
                    items.append(f'{indent}{bullet} {first}')
                    for extra in rest:
                        for line in extra.splitlines():
                            items.append(f'{indent}  {line}')
                if items:
                    out.append('\n'.join(items))
            elif name == 'blockquote':
                sub = []
                self.blocks(child, sub, list_depth)
                if sub:
                    quoted = '\n'.join(
                        '> ' + line
                        for part in sub
                        for line in part.splitlines()
                    )
                    out.append(quoted)
            elif name == 'table':
                md = self.table(child)
                if md:
                    out.append(md)
            elif name == 'hr':
                out.append('---')
            elif name in ('details', 'summary', 'figure', 'figcaption',
                          'address', 'dl', 'dt', 'dd', 'li'):
                if name in ('summary', 'dt'):
                    text = self.inline_text(child)
                    if text:
                        out.append(f'**{text}**')
                else:
                    self.blocks(child, out, list_depth)
            elif name in BLOCK_TAGS or name in ('span',):
                # Container: recurse if it holds block children, otherwise
                # treat its inline content as a paragraph (covers text that
                # lives directly in styled divs/spans).
                if any(isinstance(c, Tag) and c.name in BLOCK_TAGS
                       for c in child.children):
                    self.blocks(child, out, list_depth)
                else:
                    text = self.inline_text(child)
                    if text:
                        out.append(text)
            else:
                # Unknown/inline wrapper at block level.
                if any(isinstance(c, Tag) and c.name in BLOCK_TAGS
                       for c in child.children):
                    self.blocks(child, out, list_depth)
                else:
                    text = self.inline_text(child)
                    if text:
                        out.append(text)

    def table(self, table):
        rows = []
        for tr in table.find_all('tr'):
            cells = [self.inline_text(td).replace('|', '\\|')
                     for td in tr.find_all(('th', 'td'), recursive=False)]
            if any(cells):
                rows.append(cells)
        if not rows:
            return ''
        width = max(len(r) for r in rows)
        rows = [r + [''] * (width - len(r)) for r in rows]
        lines = ['| ' + ' | '.join(rows[0]) + ' |',
                 '| ' + ' | '.join(['---'] * width) + ' |']
        for r in rows[1:]:
            lines.append('| ' + ' | '.join(r) + ' |')
        return '\n'.join(lines)


def is_noindexed(soup):
    meta = soup.find('meta', attrs={'name': re.compile(r'^robots$', re.I)})
    return bool(meta and 'noindex' in (meta.get('content') or '').lower())


def build_twin(rel_html_path, html_content):
    """Return the twin Markdown text for one page, or None if noindexed."""
    soup = BeautifulSoup(html_content, 'html.parser')
    if is_noindexed(soup):
        return None

    conv = PageConverter(rel_html_path)

    title = ''
    if soup.title and soup.title.string:
        title = collapse_ws(soup.title.string).strip()

    description = ''
    meta = soup.find('meta', attrs={'name': 'description'})
    if meta and meta.get('content'):
        description = collapse_ws(meta['content']).strip()

    main = soup.find('main') or soup.body or soup
    for el in main.find_all(STRIP_TAGS):
        el.extract()
    for el in main.find_all(attrs={'aria-hidden': 'true'}):
        el.extract()
    for el in main.find_all(attrs={'id': lambda v: v in STRIP_IDS}):
        el.extract()

    h1 = main.find('h1')
    h1_text = conv.inline_text(h1) if h1 else ''
    heading = h1_text or title or clean_url(rel_html_path)
    if h1 is not None:
        h1.extract()  # already used as the document heading

    body = []
    conv.blocks(main, body)

    parts = [MARKER, '', f'# {heading}', '']
    if description:
        parts += [description, '']
    parts += [f'Canonical: {clean_url(rel_html_path)}', '']
    for block in body:
        parts += [block, '']
    text = '\n'.join(parts)
    text = re.sub(r'\n{3,}', '\n\n', text)
    if not text.endswith('\n'):
        text += '\n'
    return text


def collect_pages():
    pages = []
    for root, dirs, files in os.walk(ROOT_DIR):
        dirs[:] = sorted(d for d in dirs
                         if not should_ignore(
                             os.path.relpath(os.path.join(root, d), ROOT_DIR)))
        for f in sorted(files):
            if f.endswith('.html'):
                rel = os.path.relpath(os.path.join(root, f), ROOT_DIR)
                if not should_ignore(rel):
                    pages.append(rel)
    return sorted(pages)


def collect_existing_md():
    found = []
    for root, dirs, files in os.walk(ROOT_DIR):
        dirs[:] = sorted(d for d in dirs
                         if not should_ignore(
                             os.path.relpath(os.path.join(root, d), ROOT_DIR)))
        for f in sorted(files):
            if f.endswith('.md'):
                rel = os.path.relpath(os.path.join(root, f), ROOT_DIR)
                if not should_ignore(rel):
                    found.append(rel)
    return sorted(found)


def has_marker(path):
    try:
        with open(path, 'r', encoding='utf-8') as fh:
            return fh.readline().rstrip('\n') == MARKER
    except OSError:
        return False


def main():
    check = '--check' in sys.argv[1:]

    expected = {}  # rel .md path -> content
    for rel_html in collect_pages():
        with open(os.path.join(ROOT_DIR, rel_html), 'r', encoding='utf-8') as fh:
            html_content = fh.read()
        twin = build_twin(rel_html, html_content)
        if twin is None:
            continue  # noindexed
        expected[rel_html[:-len('.html')] + '.md'] = twin

    problems = []
    warnings = []
    written = deleted = unchanged = 0

    for rel_md in sorted(expected):
        abs_md = os.path.join(ROOT_DIR, rel_md)
        exists = os.path.exists(abs_md)
        if exists and not has_marker(abs_md):
            warnings.append(f'SKIP (no marker, not a twin): {rel_md}')
            continue
        current = None
        if exists:
            with open(abs_md, 'r', encoding='utf-8') as fh:
                current = fh.read()
        if current == expected[rel_md]:
            unchanged += 1
            continue
        if check:
            problems.append(('missing' if not exists else 'stale', rel_md))
        else:
            with open(abs_md, 'w', encoding='utf-8') as fh:
                fh.write(expected[rel_md])
            written += 1
            print(f'wrote {rel_md}')

    # Orphans: marker-bearing twins with no (indexable) HTML source.
    for rel_md in collect_existing_md():
        if rel_md in expected:
            continue
        abs_md = os.path.join(ROOT_DIR, rel_md)
        if not has_marker(abs_md):
            continue  # hand-written markdown: never touch
        if check:
            problems.append(('orphaned', rel_md))
        else:
            os.remove(abs_md)
            deleted += 1
            print(f'deleted orphan {rel_md}')

    for w in warnings:
        print(f'WARNING: {w}', file=sys.stderr)

    if check:
        if problems:
            for kind, rel_md in problems:
                print(f'{kind}: {rel_md}')
            print(f'{len(problems)} md twin(s) out of date '
                  f'(run: python3 scripts/generate_md_twins.py)')
            return 1
        print(f'{len(expected)} md twins up to date')
        return 0

    print(f'md twins: {written} written, {unchanged} unchanged, '
          f'{deleted} orphan(s) deleted, {len(warnings)} skipped')
    return 0


if __name__ == '__main__':
    sys.exit(main())
